# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target '新浪微博' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 新浪微博

pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'pop'

end
